### ISSUE TITLE
add a small description for ieach package

### ISSUE THREAD

**Issue by rubo77** [FreifunkMYK/gluon-packages-extra#5]
It would be helpful if you add a simple README.

I am especially interested in the gluon-autoupdater-branch-fix, how it works

**Comment by adlerweb** [comment]
Uhm - every packet got it's own readme, you just have to open the corresponding folder ;)

For autoupdater: It just checks if the locally configured branch is found inside site.conf, if not the local setting is discarded and reset to the default branch.
